name: Deploy uberli-secret-frontend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write        # needed for OIDC auth
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id:      ${{ secrets.AZUREAPPSERVICE_CLIENTID_28E5AAAFB0BB470A93549DAF0473C268 }}
          tenant-id:      ${{ secrets.AZUREAPPSERVICE_TENANTID_D41351D7FB324916AEA01A17CF8BFBCC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_36208CE4D1FE4AC589E87FA2D0B327E7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: uberli-secret-frontend   # exact App Service name
          package: .                        # deploy the whole repo
